language: java
jdk:
  - oraclejdk8

before_script:
    - wget http://services.gradle.org/distributions/gradle-3.3-all.zip
    - unzip gradle-3.3-all.zip
    - export GRADLE_HOME=$PWD/gradle-3.3
    - export PATH=$GRADLE_HOME/bin:$PATH